version: '3.7'
  
services:

    hyl_db:
        image: postgres:latest
        ports:
            - "${MY_DOCKER_IP}:${PORT_DB_EXT}:${PORT_DB_INT}"
        volumes:
            - "./../scripts-sql:/docker-entrypoint-initdb.d"
        environment:
            - POSTGRES_DB=hyl_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_PGDATESTYLE=European,SQL